schema_version = "1.0.0"
id = "modset"
version = "0.2.3"
name = "Chiro's ModSet"
tagline = "Modifier Set"
maintainer = "Chiro Fujita"
type = "add-on"
tags = ["Modifiers"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-2.0-or-later",
]